apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: js-app
  template:
    metadata:
      labels:
        app: js-app
    spec:
      containers:
      - app:
        image: public.ecr.aws/u0o2c3o6/nginx-js-static:latest
        imagePullPolicy: Always
        name: js-app
        ports:
          - containerPort: 80